# Generated by Django 4.1.4 on 2023-02-24 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default=' ', max_length=150, verbose_name='Telefono')),
                ('address', models.CharField(blank=True, default=' ', max_length=150, verbose_name='Direccion')),
                ('neighborhood', models.CharField(blank=True, default=' ', max_length=150, verbose_name='Barrio')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='Observaciones')),
                ('real_id', models.CharField(max_length=20, unique=True, verbose_name='Cedula')),
                ('is_debt_collector', models.BooleanField(default=False, verbose_name='Cobrador')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Empleado')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuarios',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
